name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web/requirements.txt
    - name: Run Tests
      run: |
         export SECRET_KEY="postgres" DB_NAME="postgres" DB_USER="postgres" DB_PASS="postgres" DB_SERVICE="postgres" DB_PORT="5432"
         python web/manage.py test
         ls web/manage.py
